### ISSUE TITLE
Default HTTPS redirection  HTTP code 301 instead of 302

### ISSUE THREAD

**Issue by petreturcu** [ionos-deploy-now/ionos-deploy-now#108]
# Feature request

Modify the default HTTPS redirection to serve a 301 Moved Permanently instead of 302 Moved Temporarily. This is with the correct .htaccess redirection setup.

## Description

At the moment the default HTTPS redirection is served with a 302 Moved Temporarily by the nginx server (before .htaccess), can this be changed to be served with a 301 Moved Permanently instead?

https://github.com/ionos-deploy-now/documentation/blob/eb0d8b8632e3e7327d0cfc4c0a48b8994986be8f/content/docs/apache-configuration-htaccess.md?plain=1#L47

## Value

This would enable google search indexing/crawling to behave better.

## Approach

I would start by checking the nginx server setup and there are other resources online:
```
server {
    listen 80 default_server;

    server_name _;

    return 301 https://$host$request_uri;
}
```

**Comment by ionos-deploy-now-support** [comment]
Hey @petreturcu, 
at the moment we're not able to do this configurationwise. 
We will look into whats has to be changed in order to do this. 
Best
Your Deploy Now Team
