### ISSUE TITLE
Cookie banner is in German (for English customer)

### ISSUE THREAD

**Issue by geoidesic** [ionos-deploy-now/ionos-deploy-now#113]
![Screenshot 2023-11-24 at 08 48 06](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/4637995/f462f81d-6dfc-459b-a5a7-d29ec5ed2f23)

**Comment by ionos-deploy-now-support** [comment]
Hey @geoidesic,  

this indeed is not an expected behavior. We will address this and
ensure that the correct cookie banner is displayed. 

Thank you for your feedback 
Your Deploy Now Team
