### ISSUE TITLE
This page lacks sufficient information for me to understand what's going on.

### ISSUE THREAD

**Issue by geoidesic** [ionos-deploy-now/ionos-deploy-now#114]
![Screenshot 2023-11-24 at 09 11 12](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/4637995/df5dfc35-3261-46b0-93bf-e1b6425813a4)

1. What does `Starter` mean?
2. What does `Static` mean? 
3. What does `Dynamic` mean?
4. Why am I being limited? I signed up and placed the order and authorised the credit card payment, now I'm being told I haven't signed up and I can't deploy? It's mixed messaging and it's confusing. 

This is the first time in this whole process of discovery that these terms have been mentioned and they are offered without explanation. You've put an obstacle in the way of my deployment without explanation. It says "but dynamic" but with a link that rushes me for another £7/month without explaining why it's necessary, nor why it's not included in the base package nor how the base package would be useful without this.

Also it mentions frameworks but it's not clear about whether it supports non-framework deployments or not. I don't fancy signing up for £7/month only to discover that it won't work for my setup.

I was hoping to test out this DeployNow this morning and I am now frustrated.

**Comment by ionos-deploy-now-support** [comment]
Hey @geoidesic, 

we decided for a model with a Basic Membership which includes 3 starter projects. 
You can book as many additional projects into your basic membership as you need. 
Not for free of course. Additional Static Projects are currently priced at 2€/$ per month and additional PHP-projects are priced at 7$ per month.

The site shows you the amount of available projects of each category. We took your feedback as opportunity to improve our documentation. 

Best
Deploy Now Team
