### ISSUE TITLE
I don't understand this page at all... where is it deploying to?

### ISSUE THREAD

**Issue by geoidesic** [ionos-deploy-now/ionos-deploy-now#116]
1. I'm expecting to be able to deploy to one of my IONOS VPS servers... but this seems to be deploying to some destination unknown that is unrelated to any of my actual server products. Not sure what use this is?

![Screenshot 2023-11-24 at 10 08 53](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/4637995/059d67f8-f96b-4e93-a9df-480ae83d6fd8)

**Comment by ionos-deploy-now-support** [comment]
Hey @geoidesic,
thank you for your feedback. 
Currently deploying to VPS servers is not in the scope of Deploy Now. 
We will communicate this more clearly. 
Best 
Your Deploy Now Team
