### ISSUE TITLE
How do I edit / delete a deployment thing (whatever they are called; projects?)?

### ISSUE THREAD

**Issue by geoidesic** [ionos-deploy-now/ionos-deploy-now#117]
1. The build failed because folder `./dist` doesn't exist. Fine... but now how do I edit this pipeline to fix that destination error? There doesn't seem to be a way. I can't even delete the thing.

![Screenshot 2023-11-24 at 10 19 08](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/4637995/331248cf-b66d-40ce-9303-4a5cf37e1ac6)

**Comment by ionos-deploy-now-support** [comment]
Hello! to delete a project, first, click on it then click on the gear wheel icon, and then delete project, it will ask you for confirmation and  your project will be deleted ![image](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/100566022/867ac53c-f591-424b-aa70-6b0e2eb0c646)
