### ISSUE TITLE
Error 403  after successfully deploying

### ISSUE THREAD

**Issue by KameterLuis** [ionos-deploy-now/ionos-deploy-now#118]
My DeployNow project successfully builds and deploys but all I get when accessing the website is Error[Optional[403]] for url ...
Any help?

**Comment by ionos-deploy-now-support** [comment]
Hey, 
for the time being, it should be fixed. 
Else please write us a mail to [deploynow-support@ionos.com](mailto:deploynow-support@ionos.com)

Best 
Your Deploy Now Team
