### ISSUE TITLE
Möglichkeit zum Löschen des gesamten Repositories

### ISSUE THREAD

**Issue by david-mentworks** [ionos-deploy-now/ionos-deploy-now#119]
Feedback zu einer Deploy Now Funktion: 

Ich würde die Möglichkeit zum Löschen des gesamten Repositories an der Stelle zum Löschen eines Projektes entfernen. Es besteht hier die Gefahr, dass man versehentlich den Haken setzt und damit großen Schaden anrichtet. Lieber nur das Projekte-Löschen an der Stelle zulassen und das Löschen von ganzen Repos nur direkt in Github durchführen lassen.

<img width="591" alt="Bildschirmfoto 2023-12-08 um 14 43 00" src="https://github.com/ionos-deploy-now/ionos-deploy-now/assets/91572929/050c2b33-8d27-4565-93cd-fb83930d139b">

Mit freundlichen Grüßen,
David

**Comment by shyim** [comment]
I would altogether remove that option. Does the Ionos app get permission to delete repositories? 😱

**Comment by ionos-deploy-now-support** [comment]
Hey, 
Thank you @david-mentworks and @shyim  for taking the time to give us your feedback. 

The sentiment in our team is that the feature is absolutely useful. We give a clear recommendation to read through the dialogue. Just like with GitHub, you have to type in the project/repo name and the tick to delete the repository is not set by default. We can only delete repositories with the express permission of the GitHub user; we are not authorised to do this on our own.

Best 
Your Deploy Now Team
