### ISSUE TITLE
Support for PHP

### ISSUE THREAD

**Issue by mmnasir** [ionos-deploy-now/ionos-deploy-now#12]
Dear Support DeployNowTeam,

I have tested your nice project but it did not work with PHP.

is there a way to run PHP and I am wondering about the MySQL Database where to be installed?

best wishes
Muhammad

**Comment by Robert95Sch** [comment]
Hi @mmnasir,

thanks for your question! Currently, Deploy Now only supports static sites, but your question is well timed.
We are currently working on PHP support incl. framework detection for Laravel and Symfony, build automation with composer and MariaDBs for every deployment. The new update will go into beta in a couple of weeks.

Stay tuned!
Robert

**Comment by Robert95Sch** [comment]
Hi @mmnasir,

I'm glad to announce that we are live with PHP Projects on Deploy Now, allowing you to deploy to a PHP 8.1 runtime, connecting to MariaDBs and automatically set up Laravel & Symfony projects. More information can be found in our [docs](https://docs.ionos.space/docs/deploy-php-apps/).

Looking forward to hear your feedback! :)
Robert
