### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by AndreasAugustin** [ionos-deploy-now/ionos-deploy-now#126]
Hi dear Ionos team,

seems there is close to no action going on here within github.com.
No commits within the whole space since some time and several issues are not answered/worked on.
Also no new features for a long time. 

Is the project **deploy now**  still active?

Am thinking about using deploy now for some production projects. From a starting point of view it looked promising. Do I need to look into other solutions?

Thanks

**Comment by ionos-deploy-now-support** [comment]
Hey,  

Thanks for your critique. Indeed you are right that it was too quiet here in the issues section. That will definitely change. 

We are busy analysing bugs in our middleware and backend at the moment and have already done a lot there. Please keep in mind that these commits are not visible here.  

We document all feature requests that are made here and consider where we see synergy effects. At the moment we can say no new features will be added in the next 3 months. 

Best
The Deploy Now Team

**Comment by AndreasAugustin** [comment]
Hi,
thanks a lot for the answer :rocket:
