### ISSUE TITLE
Deploy Now "The deployment is larger (109204614) than the allowed quota (50003968)"

### ISSUE THREAD

**Issue by DaVinci7070** [ionos-deploy-now/ionos-deploy-now#127]
Hi, we launched our website via Deploy Now a few months ago. Now we have recently changed some data (numbers). However, the deployment suddenly stopped working. We receive the following error message:

`
"The deployment is larger (109204614) than the allowed quota (50003968)" -> deploy-now/config.yaml
`

We have already tried to compress the images in the project, but the specified value ("109204614") does not decrease.
Does anyone have any idea why Deploy Now has suddenly stopped working even though no critical changes have been made? 
(Otherwise German is also possible)

Thank you very much

**Comment by ionos-deploy-now-support** [comment]
Hey @DaVinci7070, 

we will look into your issue and resolve it as soon as we can. 

Thank you 
Your Deploy Now Team

**Comment by ionos-deploy-now-support** [comment]
Hey @DaVinci7070, 
we could resolve the issue and your website is up and running. 
Sorry for the inconvenience and happy deploying! 
Your Deploy Now Team

**Comment by DaVinci7070** [comment]
ok thx, we found a work around, by redeploying the website again. But nice to here the bug is fixed
