### ISSUE TITLE
Adding issue templates

### ISSUE THREAD

**Issue by willemelis** [ionos-deploy-now/ionos-deploy-now#13]
to handle better requests to the product

sample:
https://github.com/scullyio/scully/issues/new?assignees=&labels=enhancement&template=---feature-request.md&title=

![image](https://user-images.githubusercontent.com/99724397/157424804-34901550-36b9-4823-a036-085755564309.png)

Here is a good sample of how angular handles its huge request partly automatic
https://www.youtube.com/watch?v=RaQDoDj3G8k

**Comment by willemelis** [comment]
maybe also a bug type would be useful

**Comment by Robert95Sch** [comment]
Hi @willemelis,

currently, we collect bugs in a form directly in the Deploy Now frontend and reply via mails. We think that some customers might not be willing to make their issues public. What do you think?

Thanks for the interesting example from angular. I think we do not have a problem with scalability and structure of requests yet and should not over regulate, but observe a little bit more. But of course, it makes sense to encourage users to share their ideas of how their request could be implemented.

I liked the approach @heichel used in his feature requests: "What do you want?" "Why do you want it?" "How would you implement it?". Especially the last point is very interesting to us. 

Best,
Robert
