### ISSUE TITLE
All deployments failing

### ISSUE THREAD

**Issue by mguth** [ionos-deploy-now/ionos-deploy-now#130]
Hi!

We‘re having major issues with the GitHub Action workflows (v2).

Our side of the code (a Gatsby website) hasn't changed in two months, but for about four to five weeks now, all deployments have failed after the actual build step and the upload is finished.

The breaking point seems to be when deploy now should be notified about the successful deployment.

The error message in the log is: 

> Error: Failed to inform Deploy Now of finished deployment upload: Request failed with status code 500

<img width="1175" alt="image" src="https://github.com/ionos-deploy-now/ionos-deploy-now/assets/353724/2249e4c8-e03a-44c1-840c-c601efa94021">

Additionally, I'm seeing warnings about deprecated node versions on the deploy now libraries – which might or might not be related to this.

<img width="1155" alt="Screenshot 2024-04-12 at 14 56 31" src="https://github.com/ionos-deploy-now/ionos-deploy-now/assets/353724/ea9d5741-887f-47dd-b600-e62d252605cb">

**Comment by agaengel** [comment]
Hi @mguth we are looking into the issue that the deployment is failing for you. Somehow the trigger when the upload is finished fails and there fore the new upload is cannot be used.

We added additional logging for this case could you try to deploy the project again.

Regards
Alex

**Comment by mguth** [comment]
Thanks for looking into this!

**Comment by mguth** [comment]
I’ve triggered a couple of deployments – I hope you are seeing something helpful in your logs.

**Comment by mguth** [comment]
Hi @agaengel! Just wondering - are there any updates on this? Or is there something else you recommend we do?

Thanks!

**Comment by agaengel** [comment]
Hi @mguth  

sorry for the late reply but builds are working again.

Regards
Alex
