### ISSUE TITLE
Node 20 in actions

### ISSUE THREAD

**Issue by WebDucer** [ionos-deploy-now/ionos-deploy-now#131]
# Feature request

Please update you r actions to use Node 20 instead of 16.

## Description

Node 16 is outdated and GitHub shows warnings in builds.

![Bildschirmfoto 2024-04-15 um 07 48 23](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/761881/69c39262-7f9c-4971-b57d-cf4d564d3b62)

## Value

Usage of modern and **supported** Node.js for actions.

**Comment by REKURDennis** [comment]
Any feedback? Github announced to stop the support for node16 in spring:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by WebDucer** [comment]
No, no feedback till now.

**Comment by ionos-deploy-now-support** [comment]
Hey @WebDucer and @REKURDennis, 
we're working on it right now and hope we can deploy it next week. 
Sorry for the late feedback. 
Best
Your DN Team
