### ISSUE TITLE
Cronjobs stopped working all of a sudden

### ISSUE THREAD

**Issue by michaelyahoo** [ionos-deploy-now/ionos-deploy-now#134]
I have the following snippet in my config.yaml:

`# uncomment the following lines to configure cron jobs
runtime:
  cron-jobs:
    - command: "php $HOME/htdocs/artisan schedule:run >> /dev/null 2>&1"
      schedule: "* * * * *"`
     
When I first deployed it, the cronjobs started to run as expected, but all of a sudden withouth any warning or errors they stopped working. I haven't made any commits in the meantime so I have literally no clue why they do not work anymore.

Please help!

**Comment by windsaenger** [comment]
Hi @michaelyahoo, 
we saw that you found your way to us via the Deploy Now frontend. 
Best
Chris
