### ISSUE TITLE
Site unauthorized access 

### ISSUE THREAD

**Issue by vylte-finuka** [ionos-deploy-now/ionos-deploy-now#135]
![Capture d’écran_7-6-2024_9831_www vylte-finuka com](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/123649969/109a4a24-e00f-4f79-8031-487d1812626e)
### 
Bonjour, je n'ai pas la possibilité d'affiché mon site avec NextJS avec accès interdit, j'utilise quoi comme "publish directory" ? Merci de résoudre ça !
Hello, I can't give access to my site with NextJS to client side with forbidden access, what I use like "publish directory" ? Thank you, to resolve this !

**Comment by agaengel** [comment]
Do you build your next site for static rendering?

you can reference the next documentation for static exports here: https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

**Comment by ionos-deploy-now-support** [comment]
We hope you were able to resolve the issue successfully. If you need any further assistance with the service, please don't hesitate to contact us via email at deploynow-support@ionos.com.
