### ISSUE TITLE
No delete project option in settings or mention in docs

### ISSUE THREAD

**Issue by k2lh** [ionos-deploy-now/ionos-deploy-now#136]
I come here from Heroku, where the basic CRUD for a project was easily findable and usable in the webapp itself, but here I can't find it in any of the settings. On top of that, nowhere in the documentation does it address how to close, cancel, delete, remove, or whatever command you want to call it, for a project. 

If the case is that once you create a project it's permanent, somewhere at the very top it needs to say this in big letters.

**Comment by Ap3rtur3** [comment]
Hey @k2lh,

If you want to delete a project, click on its settings (the cog wheel icon at the top right) and select "Delete project".
Maybe we should make this button a bit more prominent.

<img width="514" alt="Screenshot at Jun 27 15-03-44" src="https://github.com/ionos-deploy-now/ionos-deploy-now/assets/15201748/4de61403-8a05-487c-8c3a-1f7a8f46120e">
