### ISSUE TITLE
Change links to reflect workflow version.

### ISSUE THREAD

**Issue by k2lh** [ionos-deploy-now/ionos-deploy-now#137]
On the Production Deployment page, if I click on the settings and then click at the bottom on 'workflow configurations', I get this window:

![Screenshot 2024-06-18 at 10 46 31 AM](https://github.com/ionos-deploy-now/ionos-deploy-now/assets/5944316/8518cd68-6093-4002-8bbf-cafc4dd198ea)

If I click on "manage actions workflow" (the only one that doesn't link to the documentation but instead links to something that looks like it might actually, y'know, be a way to manage the actions (instead of just reading about them) -- it sends me to a github file that doesn't exist:

> The main branch of [repo-name] does not contain the path .github/workflows/deploy-now.yaml.

Setting aside that searching the documentation for "deploy-now.yaml" or just "yaml" gets zero results, on the build configuration page it says: 

> Configurations can be made under .github/workflows/deploy-now.yaml for workflow v1 and .github/workflows/[project-name]-build.yaml for workflow v2. More information about the Deploy Now workflows can be found under GitHub integration.

Clicking on the link for deploy-now.yaml gets me a page that says:

> v1 (projects created until 11/2022)
> A GitHub Actions workflow in .github/workflows/deploy-now.yaml runs the entire build and deployment. This workflow exists per branch to enable [Staging Deployments](https://docs.ionos.space/docs/staging-deployments).

Since it hasn't been 2022 for several years now, why does the link on the "manage actions workflow" continue to default to a file that doesn't exist and wouldn't apply anyway? Ending on the "file does not exist" page just sent me in a complete wild goose chase that ended up all the result of a link that needs updating.

**Comment by Ap3rtur3** [comment]
Hey @k2lh ,

Thank you for reporting the issue and your efforts! 
I'm sorry for the inconvenience the outdated links caused, it should be fixed now.

Best regards,
Marcel
