### ISSUE TITLE
Deploying React App white page

### ISSUE THREAD

**Issue by Pio-js** [ionos-deploy-now/ionos-deploy-now#139]
Hey everyone. I try to deploy my project, but it does not work properly or maybe I do something wrong.

I select the Static website and prefill workflow with defaults for React.
Than I go forward with the default options for Node.js (in this case v22 but I tried the v18 too, it is installed in my machine).
In GitHub actions I can see that it creates compressed static files during the build. But during the deploy are not uploaded on the server, because are not there. I can see just image folders and index.html and robots.txt, manifest.json and logs folder. The static folder is missing.

Any suggestion?

**Comment by Ap3rtur3** [comment]
Hello @Pio-js,

it looks like you configured `public` as the deployment folder, but react-scripts should create a `build` folder during `react-scripts build` according to the [docs](https://create-react-app.dev/docs/production-build). 
Try setting `build` as deployment folder in your workflow files. Alternatively you can recreate the project in the setup wizard with the correct deployment folder.

**Comment by Pio-js** [comment]
Hi @Ap3rtur3,

thanks a lot. This was the problem. Now it is public! :) Have a nice weekend!
