### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by YannBriand** [ionos-deploy-now/ionos-deploy-now#19]
# Feature request

## Description

What would you like us to add or improve?
I need a SSR Node.js for deploying an Angular Universal SPA.

## Value

How would this feature or improvement create value for you?
It would allow me to deploy my application with a complete SEO optimization.

## Approach

How would you implement this feature if you were us?
With a step-by-step tutorial.

**Comment by Robert95Sch** [comment]
Hi @YannBriand and thanks for your request.

SSR with Node.js was also discussed in [this request](https://github.com/ionos-deploy-now/ionos-deploy-now/issues/8). I'll close this request for now and keep you updated. Would it be okay for you if we reach out to you once we start working on a prototype to get some feedback?

Best,
Robert
