### ISSUE TITLE
TEST issue

### ISSUE THREAD

**Issue by hunsalz** [ionos-deploy-now/ionos-deploy-now#2]

**Comment by pfeifferch** [comment]
Guten Morgen 

Ich habe "Deploy Now Starter Membership" bestellt und mit GitHub verbunden.  
Weiter geht es aber nicht, ich bekomme immer nur den "Connect your GitHub account" screen (wenn überhaupt, oftmals werde ich mehrmals hintereinander auf die https://mein.ionos.de/product-overview zurück geleitet bevor ich auf ionos.space bleiben kann) zu sehen. 
Egal ob bestimmte oder alle Repository, ob suspendet oder aktiv, selbst ein Löschen und neu einrichten haben daran nichts geändert. 

Ein Support für Deploy Now gibt es in den Kontakten noch nicht. 
An wen kann ich mich wenden?

**Comment by coder-hugo** [comment]
Hallo @pfeifferch,

bei dem beschriebenen Problem hat es sich um einen temporären Fehler gehandelt. Dieser ist mittlerweile behoben und Deploy Now funktioniert wieder.
