### ISSUE TITLE
IONOS.space workflow



### ISSUE THREAD

**Issue by pfeifferch** [ionos-deploy-now/ionos-deploy-now#22]
Guten Morgen. 

Wurden Serverseitig etwas verändert bezüglich IONOS.space workflow?

Ich verwende immer noch die /.github/workflows/deploy-now.yaml

Bekomme aber seit heute Nacht nur noch Fehler.

Annotations

1 warning

Unexpected input(s) 'bootstrap-deploy', 'remote-host', 'storage-quota', valid inputs are ['entryPoint', 'args', 'service-host', 'api-key', 'project', 'branch-id', 'dist-folder', 'runtime-placeholder-files']

bzw

Warning: Unexpected input(s) 'bootstrap-deploy', 'remote-host', 'storage-quota', valid inputs are ['entryPoint', 'args', 'service-host', 'api-key', 'project', 'branch-id', 'dist-folder', 'runtime-placeholder-files']

**Comment by pfeifferch** [comment]
name: Deploy Now

on:
  - push
  - workflow_dispatch

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: ${{ secrets.IONOS_PROJECT_ID }}
          service-host: api-eu.ionos.space
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Deploy build
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          bootstrap-deploy: ${{ steps.project.outputs.bootstrap-deploy }}
          branch-id: ${{ steps.project.outputs.branch-id }}
          dist-folder: ./
          project: ${{ secrets.IONOS_PROJECT_ID }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          service-host: api-eu.ionos.space
          storage-quota: ${{ steps.project.outputs.storage-quota }}

**Comment by ionos-deploy-now-support** [comment]
Hi und danke für den Hinweis.

Wir werden zeitnah ein Update ausrollen, dass die Warnmeldung beseitigen wird.
Gibt es Fehler beim Ausführen des Workflows oder bleibt es bei der Warnung?
Wir würden vermuten, dass das Deployment weiterhin problemlos funktioniert.

Viele Grüße

**Comment by pfeifferch** [comment]
Leider häng es sich komplett auf und es geht überhaupt nichts mehr. 

Wird das selbe Projekt mit identischer Einstellung als neuer Branch gespeichert, läuft es durch. 


Gibt es ei  Limit für die Anzahl gestarteter Workflows? Wenn ja, ist das Limit auf Zeit oder eine Gesamtzahl?

**Comment by ionos-deploy-now-support** [comment]
Es gibt ein Limit für die Gesamtbuilddauer, siehe [hier](https://github.com/pricing#compare-features).

Könntest du uns den Link zum Repository kurz zukommen lassen, bzw. uns dazu einladen, falls es ein privates repository ist?

**Comment by hunsalz** [comment]
@pfeifferch - I close this issue. If you still face problems please drop us again an issue or a bug report. Thx
