### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by DGINXREAL** [ionos-deploy-now/ionos-deploy-now#25]
Hello,

i get permanently this error. I try different projects, public and private repositories. Everytime the same error.

![Error](https://cdn.dginx.de/p/dginx-sharing/msedge_kFcN5c5G4g.png)

**Comment by mandrasch** [comment]
Same here, error in chrome dev tools is:

> message: "The flag overwriteWorkflow is mandatory"

(Wanted to try PHP project with simple build steps nodejs / npm ci and composer install)

**Comment by DGINXREAL** [comment]
Its true i have the same error inside the console 

POST https://api-eu.ionos.space/v2/github/projects -> 400
`{"message":"The flag overwriteWorkflow is mandatory","violations":[]}`

**Comment by DGINXREAL** [comment]
I can fix the error. I retry it with POSTMAN and resend the request with the missing 'overwriteWorkflow ' flag and set it on 'true' inside the json.  Project was created.

**Comment by Freezle** [comment]
Hi @DGINXREAL, Hi @mandrasch,

thanks for your feedback and the ticket here. We have looked at the issue and released a bugfix. You should now be able to create your project. Whereby the workaround from you, @DGINXREAL, is of course very cool done, but for some users then a bit too complicated. ;)

Sorry for the problems with the setup wizard, we wish you a lot of fun with Deploy Now and promise that we won't stop improving!

Thanks for your feedback!

Kind regards
Eric
