### ISSUE TITLE
Löschen von einzelnen Commands löscht immer letzten

### ISSUE THREAD

**Issue by DGINXREAL** [ionos-deploy-now/ionos-deploy-now#26]
Hallo,

ich habe einen neuen Bug entdeckt im Wizard for Laravel Projekte.

Siehe Video https://cdn.dginx.de/p/dginx-sharing/msedge_Wd0qlqEqIi.mp4

Wenn man mehrere Commands hat und will einen aus der Mitte löschen, wird immer der letzte gelöscht.

**Comment by Freezle** [comment]
Hi @DGINXREAL ,

danke für das Melden des Bugs. Wir konnten ihn reproduzieren und arbeiten am Fix.

Viele Grüße
Eric

**Comment by Freezle** [comment]
Hi @DGINXREAL ,

wir haben den Bug nun gefixt und ein neues Release ausgerollt.

Vielen Dank für dein Feedback!

Viele Grüße
Eric
