### ISSUE TITLE
Edit the Crontab to run php Code in an PHP "Deploy Now" Project

### ISSUE THREAD

**Issue by leobm** [ionos-deploy-now/ionos-deploy-now#27]
# Feature request

## Description
What I could need in a Laravel project would be the possibility to setup the crontab to start the Laravel Task-Scheduler.

see here:
https://laravel.com/docs/9.x/scheduling#running-the-scheduler

Or is that somehow possible with Deploy Now?

Cheers,

Felix

**Comment by leobm** [comment]
ok, as a workaround  you could execute a laravel command after the deployment at runtime. You would then have to make a commit in the project, so that the deployment (github action) is triggered. 


https://docs.ionos.space/docs/runtime-configuration/#config-file-templating
"You have the option to execute commands on the runtime before and after each deployment. Visit [deployment configuration](https://docs.ionos.space/docs/deployment-configuration) for more information. Deploy Now currently does not offer the option to execute runtime commands at any time, neither via SSH or e.g. cronjobs.!

**Comment by Nordlicht13** [comment]
Hi @leobm ,

thanks for your feedback and your feature request! Cronjobs are definetly on our bucket list. :+1: 

I know, it's very dirty, but for the moment you could use the following fix: http://novate.co.uk/help-my-host-does-not-support-cron-jobs/.

We let you know, when we implemented the cronjob feature. :)

Kind regards
Eric

**Comment by Freezle** [comment]
Hi @leobm ,

thanks for your feedback and your feature request! Cronjobs are definetly on our bucket list. +1

I know, it's very dirty, but for the moment you could use the following fix: http://novate.co.uk/help-my-host-does-not-support-cron-jobs/.

We let you know, when we implemented the cronjob feature. :)

Kind regards
Eric

**Comment by leobm** [comment]
Hi @Freezle
ok, that's a workaround i can live with for now.

 thanks, Felix

**Comment by Robert95Sch** [comment]
Hi @leobm, 

Deploy Now now supports Cron Jobs ([learn more](https://docs.ionos.space/docs/cronjobs/)). Currently, users can simply list them in a config file. We will most likely also enable cron job creation in the UI.

Thanks again for your feedback! :)
