### ISSUE TITLE
Website breaks when I refresh (F5) the page if the path is not empty

### ISSUE THREAD

**Issue by RamiroPastor** [ionos-deploy-now/ionos-deploy-now#3]
Hi, I'm trying the Deploy Now feature, but I cannot find a way to solve this problem:

I have built a website with React, and it works fine only if I navigate directly to the root path, but refreshing a page other than the root page or navigating directly to a non-root path breaks the website.

I used to host my website on netlify, and this problem was solved with a file called `_redirects` placed in the public folder of my react project, with a single line of code inside: `/* /index.html 200`. Is there any way to replicate this with Deploy Now?

### Steps to reproduce the problem:

1.  Open [https://ramiropastor.es/](https://ramiropastor.es/)
2.  Click the button in the middle of the screen, which directs you to [https://ramiropastor.es/home](https://ramiropastor.es/home )
3.  Refresh the page (F5)

Or alternatively, you can navigate directly to https://ramiropastor.es/home and it won't work. I use `react-router-dom` to simulate routes in the react project by the way.

Thanks in advance.

**Comment by Freezle** [comment]
Hi Ramiro, I'm Eric from the Deploy Now team. Thanks for your issue here.

Please commit the following content to a file called `.htaccess` in `public` folder to your repository.

```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

Now it should work!

Have a great day and thanks for using our product! :)
Eric

**Comment by RamiroPastor** [comment]
Perfect, this solves the problem. Thanks.
