### ISSUE TITLE
Make deploying possible

### ISSUE THREAD

**Issue by DanSchrader** [ionos-deploy-now/ionos-deploy-now#30]
## Value Preposition

**As a** user
**I need** to be able to change my GitHub-repos, after deploying failed,
**to be able to** do troubleshooting by trying an empty project or something similar, before I open an issue.

## Description

![issue-ionos-deploynow](https://user-images.githubusercontent.com/98756494/167222523-9d7921df-e93e-4346-9089-e8b56b3eb62c.png)

## Acceptance Criteria

- [ ] selectable repos need to be changed in the drop-down menu
- [ ] new empty projects should be selectable for testing
- [ ] deploying a simple React-single-page-app without backend shows the website or an error message
- [ ] no blank page or error message 403 is shown
- [ ] better explanations for commands, environment variables and output path are shown

**Comment by RamiroPastor** [comment]
I do not work for ionos, but this may help you:

In your React project, inside the `public` folder:

1.  Make a new file called `_redirects` (just like that, no extension) and inside the file write `/* /index.html 200`
2. In that same folder, make a new file called `.htaccess` and write inside:

```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

But yes, even if this works, WE THE CLIENTS SHOULD BE ABLE TO *ADD NEW INFO OR EDIT THE INFO THAT WE INTRODUCED WHILE STARTING A DEPLOY-NOW PROJECT* WITHOUT GOING CRAZY TRYING TO UNDERSTAND THE `deploy-now.yaml` FILE

**Comment by Robert95Sch** [comment]
Hi @DanSchrader ,

thanks a lot for your feedback. I can understand your frustration. I hope the solution from @RamiroPastor will resolve your main problem. 

Did I understand that correctly, you would like to have an option to switch the repository from the project to a different repository that is empty (newly created in your GitHub account by the Deploy Now App)? Would you then expect that the GitHub Actions workflow from your initial repository is copied into the new one?

Alternatively, we could think about adding a React Sample project to the existing samples under "Third party repository", which you could use to create an additional project.

Kind regards,
Robert
