### ISSUE TITLE
Single github directory can deploy to multiple domains

### ISSUE THREAD

**Issue by jasontd92** [ionos-deploy-now/ionos-deploy-now#33]
# Feature request

## Description

Single github directory could have the ability to deploy to multiple domains or subdomains. Right now from what I can tell, it is only possible to deploy with a one-to-one relationship (one repo to one domain). 

## Value

My specific use case is so that I can deploy the same site to multiple subdomains. It is a B2B site, so each business has their own unique subdomain that customers use to access their page. Currently, I haven't found a way to do this with existing Deploy Now capabilities. In the meantime, I am achieving the same functionality using React Router.

## Approach

I'm unfamiliar with how deploy now works, so I can't offer much of value as far as how to implement this feature, or even if it has a simple solution.

**Comment by hunsalz** [comment]
Hi @jasontd92,

first of all thx for your request.

Actually, we had a similar discussion just a few days ago. - But first, you're right. Currently you can connect a repo just once and you can connect only one custom domain to your project. 

From you description I understand that you want to connect multi domains per project. It's not that you want to deploy a repository multiple times? That's an other way we thought about. We would say to "spawn" an instance. This could be an use case for an API for example. 

If I'm guessing wrong please give us a short notice.

Cheers,
@hunsalz

**Comment by jasontd92** [comment]
Yes correct, the end goal is spawning multiple instances off of a single repository.

**Comment by REKURDennis** [comment]
I have the same use case. Right now I created a copy of my GIT repository, which is sadly a really ugly workaround.

**Comment by Robert95Sch** [comment]
Hi @jasontd92 & @REKURDennis, we've launched this feature yesterday, it's called [Multi Deployments](https://docs.ionos.space/docs/multi-deployments/). You can now add additional production deployments on the project detail page. It would be great if you could share your feedback for this new feature!
