### ISSUE TITLE
Ionos Github Action requires update to Hugo Extended 0.95

### ISSUE THREAD

**Issue by de-barros** [ionos-deploy-now/ionos-deploy-now#35]
I'm running a wowchemy site on Deploy Now with Hugo, as provided by Ionos (initially set up with [this](https://github.com/ionos-deploy-now/hello-hugo) Ionos GitHub Action workflow). 

Recently, wowchemy [started requiring](https://github.com/wowchemy/wowchemy-hugo-themes/releases) Hugo Extended 0.95, but the workflow only pulls 0.84.4. Under "build project" the ionos-space workflow ends in an error "Process completed with exit code 2."

I suspect this gets resolved once you update the Hugo version in the workflow. Can you help me update it?

**Comment by de-barros** [comment]
![image](https://user-images.githubusercontent.com/20994418/170124787-313a09f7-c601-4540-8704-a3284674259d.png)

![image](https://user-images.githubusercontent.com/20994418/170125012-af01b690-407c-4d13-bffc-875fecd495de.png)

**Comment by de-barros** [comment]
☝️ @coder-hugo, thank you in advance for your help with this!

**Comment by agaengel** [comment]
hi @de-barros 

you can manage the hugo version in your workflow located at .github/workflows/deploy-now.yaml in the repository

there should be a section like:
      - name: Setup Hugo
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.8.4'
          extended: true


you can define the hugo verison by changing the line hugo-version: '0.8.4' to hugo-version: '0.99.1' or hugo-version: 'latest' 

Regards
Alex

**Comment by de-barros** [comment]
Thanks, @agaengel!
