### ISSUE TITLE
Making all pages in a static Next.js page avaiable.

### ISSUE THREAD

**Issue by WestfalNamur** [ionos-deploy-now/ionos-deploy-now#38]
# Feature request
Making all pages in a static Next.js page avaiable.

## Description
I would like to have all pages (/pages) in a Nextjs project available on a deployed website. So far I get "Forbidden" when accessing one beside the home page. On tests on Vercel it worked. 

## Value
We can take more advantage of our website.

## Approach
I am not sure if it is a bug or missing feature.

**Comment by hunsalz** [comment]
@WestfalNamur - Sounds like this [issue](https://github.com/vercel/next.js/discussions/10522) to me. The "Forbidden" comes probably from the httpd default config "+MultiViews". 

Deploy Now is based on a LAMP-stack. NextJS is based on React. That means you need to create a .htaccess file: https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing

I didn't try the React solution myself so far. But I'm aware of a similar case with Vue-Apps: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations - I personally would prefer the solution described there. 

If it's working to you, I would be glad to hear from you.

**Comment by hunsalz** [comment]
@WestfalNamur - Did you retry my suggestion with your project?

I added a section for SPAs in Deploy Now [Documentation ](https://docs.ionos.space/docs/apache-configuration-htaccess/#single-page-apps-like-angular-reactjs-vuejs). I hope this is helpful.

Closing this issue. Please re-open if you face still problems with my solution.
