### ISSUE TITLE
Stuck in connection to github

### ISSUE THREAD

**Issue by hoochicken** [ionos-deploy-now/ionos-deploy-now#41]
Hi,

**(1) Stuck in connection to github**

I tried connect ionos to github, but it doesn't seem to work. So I can't get to any configuration of ionos.
Could you plz fix what's wrong with my account,

**(2) Feedback & Support > Report a bug**

I cannot report a bug, I guess. The GUI has a somewhat strange behaviour.
The "Affected repository" field seems to be a mandatory field.
Yet in my case: 

* there is no connection to github
* => there are no repositories displayed 
* => can't fill out form properly
* => clicking "Send" button
* => form popup closes
* => NO message about what just happend, I would have expected:
    * EITHER "You bug report has been sent successfully. We'll come back to you ..."
    * OR "Some error has occured. The error is ..."
    * OR "Affected repository is a mandatory field. Plz select repository"

Quick fix would be, so add an additional option to "Affected repository" select like " - general problem - "

Greetings
Mareike

**Comment by Robert95Sch** [comment]
Hi @hoochicken,

there was indeed a bug in the bug report form. Thank you so much for the hint! We just fixed it. Selecting a repo is not mandatory in this form - but of course it doesn't make sense to show it for users that haven't connected GitHub yet. 

As the form should work again, could you maybe create a new small bug report? Then we have the meta infos from your customer account and can check what's wrong. 

Sorry for the inconvenience.

Best,
Robert
