### ISSUE TITLE
IONOS Deploy Now doesn't work... It just prompts me to sign into Github over and over

### ISSUE THREAD

**Issue by sontgaming** [ionos-deploy-now/ionos-deploy-now#42]
I bought the membership for deploy now, and read the documentation to use it. Here I am at **https://ionos.space/github-connection**, and it prompts me to sign in to GitHub. I install the application and give it access to all my repositories and hit save, It then redirects me to **https://ionos.space/github/install?code=73fd47b62df40de56850&installation_id=27637940&setup_action=update&state=installation** where it loads for a few seconds, then turns back into  **https://ionos.space/github-connection** where it again prompts me to sign in to GitHub in an endless cycle.

 I've put in a bug report, which shut the page down for maintenance for a couple hours and did nothing. I contacted customer support which just told me to read the documentation.

I used inspect element to check the console and it showed this

Failed to load resource: the server responded with a status of 500 ()
chunk-vendors.31bdd3b9.js:27 Uncaught (in promise) Error: Request failed with status code 500
    at t.exports (chunk-vendors.31bdd3b9.js:27:81225)
    at t.exports (chunk-vendors.31bdd3b9.js:41:215823)
    at XMLHttpRequest.M (chunk-vendors.31bdd3b9.js:96:62048)

help

**Comment by MM53** [comment]
Hi @sontgaming,

unfortunately we added a bug to the github connection process in our last release which prevents creating new connections. Sorry for the inconvenience.

We have fixed this bug now, so everything should work as expected. Could you please try to connect your account again? If you still have any issues, please let us know. 

Best regards, 
Marlon
