### ISSUE TITLE
PHP Extensions

### ISSUE THREAD

**Issue by awillrich** [ionos-deploy-now/ionos-deploy-now#43]
Für mein Projekt benötige ich PHP Extensions wie ext-zip und ext-gd.
Leider habe ich in der Dokumentation keine Möglichkeit gefunden diese zu installieren/aktivieren.

**Comment by agaengel** [comment]
Hi @awillrich,
verstehe ich das richtig, dass diese Extension während des Bau Schrittes des Projects gebraucht werden.

Die Extension für den Bau können in dem deploy-now workflow angepasst werden (.github/workflows/deploy-now.yml im Repository).

Dort sollte es einen Step geben, der die php-actions/composer@v6 verwendet
Bei der Action kann man die extension im with angeben z.B. php_extensions: gd zip
weitere Information dazu in der readme der [composer action](https://github.com/php-actions/composer)

Ich hoffe das Hilft, damit sie ihr Project mit Deploy now bauen können.

**Comment by awillrich** [comment]
Das hat geholfen. Vielen Dank!
