### ISSUE TITLE
Support of Nuxt 3

### ISSUE THREAD

**Issue by kjanusz** [ionos-deploy-now/ionos-deploy-now#44]
When will you support the nuxt 3 version?

**Comment by ionos-deploy-now-support** [comment]
Hello, thanks for reaching us and for your request ... We had to solve an issue with our `deploy-to-ionos-action.` With the new release of our Action NuxtJS works out of the box with Deploy Now using dist as deployment directory. 
Also, I would like to point out that only static site generation works with NuxtJS with Node.js is not available yet.

Thank you for pointing out this issue.

**Comment by kjanusz** [comment]
Hello, thanks! 

I have a question about this: I currently have some projects with Nuxt 3 SSR on IONOS. That's why I modified the previous script (see https://github.com/ionos-deploy-now/hello-nuxt/issues/5). 

Does that mean I can go back now to dist?

```yml
 #dist-folder: .output/public
 dist-folder: dist
```
Do I have to do anything else?

What about the adjustment?
```
<IfModule mod_mime.c>
  AddType text/javascript js mjs
</IfModule>
```

Could you please publish an hello-nuxt-3 example below [as for Nuxt 2](https://github.com/ionos-deploy-now/hello-nuxt)? I think that would be very helpful.

**Comment by ionos-deploy-now-support** [comment]
> Does that mean I can go back now to dist?

Yes, you will be able to use `dist` as publish folder again, we are now supporting symlinks as well.

> Are both variants supported by the new release of deploy-to-ionos-action? Do you recognize that automatically?

Deploy Now currently only supports static hosting with` nuxt generate`. 

> Do I have to do anything else?

You will also need an `.htaccess` file to support the `.mjs` extension. 

First create a `.htaccess.template` file inside your `.deploy-now` directory like described [here](https://docs.ionos.space/docs/apache-configuration-htaccess/#templating-htaccess).
```
<IfModule mod_mime.c>
    # add support for ECMAScript modules
    AddType text/javascript mjs js
</IfModule>
```
Paste the workflow step below in your `.github/workflows/deploy-now.yaml` before the Deploy to IONOS step.
It will generate the `.htaccess` file in your publish directory.
```
- name: Render templates
  if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
  uses: ionos-deploy-now/template-renderer-action@v1
  id: template
  with:
    output-directory: .output/public
    secrets: |
```
Now the `.htaccess` file should be deployed into your dist folder.

We created a [Nuxt 3 sample](https://github.com/ionos-deploy-now/hello-nuxt3) for you and are extending the detection to incorporate the manual adjustments above.

We hope this helps and thank you for pointing out this issue

**Comment by Robert95Sch** [comment]
Hi, we've just released mime type support on our infrastructure. The above mentioned adaptions of the .htaccess and the render templates step in GitHub Actions is not necessary anymore. 
Happy deploying!
