### ISSUE TITLE
Connect Ionos account to multiple Github organizations

### ISSUE THREAD

**Issue by florolf1** [ionos-deploy-now/ionos-deploy-now#47]
i have connected my ionos account to my github organization in which i am the owner of.
Now i want to deploy another repository from another organization in which i am also an owner of.
Is this possible to connect my ionos account to multiple organisations?

If not, what is the workaround?
If i remove the access to my first organization and connect my second organization, will the repos which are already deployed stayed untouched?

**Comment by ionos-deploy-now-support** [comment]
Thank you for reaching out.
At this moment we only support 1 Deploy now contract connected to 1 organization and only 1 Deploy Now contract per Ionos account.

for your second question, if you remove access to your organization, those will not get deleted but you will receive an error. as it needs to be connected to that specific organization.
