### ISSUE TITLE
Second Project with same Repo and another Branch

### ISSUE THREAD

**Issue by mongroove** [ionos-deploy-now/ionos-deploy-now#48]
why can't I select the same repository with a different brunch for another project. This would be very important to me.
Currently it says "... in use"

**Comment by ionos-deploy-now-support** [comment]
Hi! i see you are using Staging for your project, are you still having problems?

**Comment by mongroove** [comment]
Yes, still the same problem. I am forced to use an IONOS subdomain with their solution. But I don't want to send this to my customers. I want to use the staging version with my own subdomain (ex. staging.mydomain.com)

**Comment by cellyme** [comment]
Hello @Robert95Sch ,

I would love to see this feature being added. I actually purchased the product thinking you would be able to deploy your stage onto your subdomains. I was shocked to see that you cannot do that yet. 

Kind regards
Marcel
