### ISSUE TITLE
Connection with BitBucket

### ISSUE THREAD

**Issue by SoloEdrei** [ionos-deploy-now/ionos-deploy-now#52]
# Feature request
Connection with bitbucket

## Description

In my organization, we work with Bitbucket we're really going to appreciate if is possible to add a Bitbucket integration to deploy repositories from there.

## Value

It helps us to keep using Bitbucket.

## Approach

Adding an SSH key support to clone the repository.

**Comment by Robert95Sch** [comment]
Hi @SoloEdrei ,

thanks for considering Deploy Now. 
Unfortunately, we do not have Bitbucket support in our backlog, but we might consider it in the future.

Thanks for your feedback,
Robert
