### ISSUE TITLE
Connect multiple sub-domains to one DeployNow target

### ISSUE THREAD

**Issue by NeoSakuragi** [ionos-deploy-now/ionos-deploy-now#53]
# Feature request

## Description

Connect multiple sub-domains to the same DeployNow target using 1 github repo. For example customer1.myapp.com and customer2.myapp.com would hit the same hosted application.

## Value

It would enable applications to be multi-tenant by steering the same application to different databases depending on the sub-domain. For example:
-> customer1.myapp.com would run a given DeployNow instance with a config relevant for customer1 (db credentials)
-> customer2.myapp.com would run the exact same DeployNow instance, but with a config relevant to customer2.

## Approach

Today Ionos offers the possibility to link multiple sub-domains to the same "static" web folder. I would probably extend that concept to have sub-domains linked to the same DeployNow instance.

**Comment by ionos-deploy-now-support** [comment]
Thank you for your Feature request,  sadly at this moment it is not in our roadmap

**Comment by Robert95Sch** [comment]
Hi @NeoSakuragi , we are currently working on a feature that allows you to deploy one repository to multiple runtimes, each with one web spaces and databases. GitHub Actions would run one build step, and afterwards multiple deployments. Would that help you for your use case?

**Comment by Robert95Sch** [comment]
The new [Multi Deployments](https://docs.ionos.space/docs/multi-deployments/) feature is now implemented @NeoSakuragi
