### ISSUE TITLE
Support for additional php extensions

### ISSUE THREAD

**Issue by Rathch** [ionos-deploy-now/ionos-deploy-now#54]
# Feature request

## Description

i would like to have the possibility to add additional php extensions like ext-zip 

## Value

tolls like the ckeditor get useable

**Comment by ionos-deploy-now-support** [comment]
thank you for your questions
As for now, it is not possible to add additional PHP extensions,
this is something that might change in the future,

**Comment by ionos-deploy-now-support** [comment]
Hi @Rathch,

we've discussed your request once again. If you want to need the php extension during the build process, you can add it like describes [here](https://github.com/marketplace/actions/composer-php-actions#including-php-extensions). Regarding the web space itself, the ext-zip is already activated.

Thanks for using Deploy Now and have a nice week!
