### ISSUE TITLE
php ext-zip is not working

### ISSUE THREAD

**Issue by Rathch** [ionos-deploy-now/ionos-deploy-now#57]
i can not install the ext-zip 
https://github.com/Rathch/dskl-deploy/actions/runs/3264812877/jobs/5366051287

**Comment by agaengel** [comment]
please install the extension via 
`php_extensions: zip `

**Comment by agaengel** [comment]
@Rathch did this work for your project ?

**Comment by Rathch** [comment]
yes thx
