### ISSUE TITLE
Deployment does not work, each failed

### ISSUE THREAD

**Issue by aracnathea66** [ionos-deploy-now/ionos-deploy-now#58]
Hello,

I have deployed my GitHub code several times on Ionos now with several different repositories and changed the data volume and added the new node.js but still, it does not work. 

I need urgently your help with the deployment!!! I pay for your service for nothing until now although I have sent two bug reports to your team already. Guess what... now answer yet. 

1. How can I successfully deploy my webpage? This is the GitHub deployment notice: "The deployment is larger (138947430) than the allowed quota (50003968)"
2. Why does my account still show that I am not using my domain? This is what I thought I would do with the deployment. 

Anyway, does your deployment now work? How can it be that each deployment fails? 

Please help me soon with that issue or I need to find another solution.

**Comment by ionos-deploy-now-support** [comment]
Hello @aracnathea66,
please accept my apologies for the late response to your message.
Unfortunately, I was unable to locate your account and investigate the deployment errors.
I would like to inform you, though, that during the time past after your message, we have improved greatly the Deploy Now and we have recently launched a new version of the platform.
If you would like to give it a try, we will be thrilled to help you deploy your website with us.
