### ISSUE TITLE
[Laravel] php artisan migrate --force -n Failing

### ISSUE THREAD

**Issue by pTinosq** [ionos-deploy-now/ionos-deploy-now#63]
I just opened issue #62 but had a look earlier in my deployment logs to see that I had another issue under the same job (deploy-to-ionos).

This time, the error is thrown by the `php artisan migrate --force -n` command.

Here is the log:
```
Running the remote command: php artisan migrate --force -n

In Connection.php line 760:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for {{.runtime  
  .db.host}} failed: Name or service not known (SQL: select * from informatio  
  n_schema.tables where table_schema = {{.runtime.db.name}} and table_name =   
  migrations and table_type = 'BASE TABLE')                                    
                                                                               

In Connector.php line 70:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for {{.runtime  
  .db.host}} failed: Name or service not known                                 
                                                                               

In Connector.php line 70:
                                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo for {{.runtime.db  
  .host}} failed: Name or service not known                                    
                                                                               

Error: Error running the remote command
```

It seems that the {{.runtime.db.host}} has not been replaced in the .env file. I can confirm this by going into the Deployment Viewer. When I go to .env file any of the `{{ .example. }}` variables have not been replaced.

**Comment by MM53** [comment]
Hi @pTinosq,

sorry for the delayed reply.

Looks like there was an issue with the templating in your project. Your data shows that you used our old template syntax like it was shown in the product video mentioned in #62. A few weeks ago we changed the templating to improve the support for multi deployment projects. I assume your build workflow was already generated with the new template action which isn't compatible with the old syntax. Please checkout our documentation for the required changes: https://docs.ionos.space/docs/runtime-configuration/#application-configuration
 
 Best regards,
 Marlon
