### ISSUE TITLE
domain extension

### ISSUE THREAD

**Issue by RETOSENERGETICOS** [ionos-deploy-now/ionos-deploy-now#67]
I have a Deploy Now product where the repository is uploaded and Deploy does it graphically. This one already has a domain that I assigned to it but I don't want /x/x/x to appear. Is there a way to put the extension I want? For example, instead of https://grretosenergeticos.com/public/app/herramientas/agregar I want https://grretosenergeticos.com/privado/herramientas to appear. 
![captura](https://user-images.githubusercontent.com/115562084/207188958-5a4757a9-6819-45fb-a597-05586affe37f.png)

**Comment by druvio** [comment]
Hello,
thank you for your feedback.
We are looking into your request and we will get back to you as soon as possible.

**Comment by druvio** [comment]
Hello @RETOSENERGETICOS,
URL rewrite and remapping are achieved through .htaccess.
Please find more details about how to set it up at the following links:
[https://httpd.apache.org/docs/2.4/rewrite/remapping.html](https://httpd.apache.org/docs/2.4/rewrite/remapping.html)
[https://httpd.apache.org/docs/2.4/urlmapping.html](https://httpd.apache.org/docs/2.4/urlmapping.html)
[https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html)
