### ISSUE TITLE
[FEATURE] use vite instead of laravel-mix

### ISSUE THREAD

**Issue by AndreasAugustin** [ionos-deploy-now/ionos-deploy-now#72]
# Feature request

## Description

When creating a new project, the setup contains per default laravel-mix which uses webpack.
Laravel is migrating to [vite](https://vitejs.dev/) what is mentioned within the laravlel [site](https://laravel.com/docs/9.x/vite).

It would be nice to have vite per default instead of webpack.

## Value

Vite is super fast during build time giving a much nicer development experience.

## Approach

Use the setup given per default when bootstraping a new laravel project.

**Comment by AndreasAugustin** [comment]
**Remark:**

Following steps are needed for the migration:

- add a `postcss.config.js` file into the root directory with content
```js
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
  ]
}
```
- add a `vite.config.js`  file into the root directory with content
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
});
```
- modify the `package.json`
```json
{
    "private": true,
    "scripts": {
        "build": "vite build",
        "dev": "vite"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.4.0",
        "alpinejs": "^3.4.2",
        "autoprefixer": "^10.4.2",
        "axios": "^0.25",
        "laravel-vite-plugin": "^0.7.2",
        "lodash": "^4.17.19",
        "postcss": "^8.4.6",
        "postcss-import": "^14.0.2",
        "tailwindcss": "^3.0.18",
        "vite": "^4.0.0"
    },
    "engines": {
        "node": "16"
    }
}
```
- delete `webpack.mix.js`
- add `/public/build` to `.gitignore`

**Comment by ionos-deploy-now-support** [comment]
Thank you for your contribution and your requests! we will look into them

**Comment by Freezle** [comment]
Hi @AndreasAugustin,

we updated our Laravel Starter today - now we use Vite instead of Mix.

Kind regards
Eric

**Comment by AndreasAugustin** [comment]
Hi @Freezle 
great! now also in adddition `npm audit` should be fine ;) 

Thank you very much for doing the switch!
