### ISSUE TITLE
[CONTRIBUTION] please add a security policy into the repository

### ISSUE THREAD

**Issue by AndreasAugustin** [ionos-deploy-now/ionos-deploy-now#73]
# Feature request

## Description

please add a `SECURITY.md` file into the repository.
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

## Value

Currently it is not known how to report security issues in a secure manner.

**Comment by ionos-deploy-now-support** [comment]
Thank you for your contribution and your requests! we will look into them

**Comment by Robert95Sch** [comment]
I've added a policy to this repository. Thanks for the feedback @AndreasAugustin :-)
