### ISSUE TITLE
[Question/Docs] security databases

### ISSUE THREAD

**Issue by AndreasAugustin** [ionos-deploy-now/ionos-deploy-now#76]
# Question

Just a short question (was not able to find something related in the docs)

- is the data within the databases (mariadb) encrypted@rest?
- are the databases in its own subnet (network wise) or publicly accessible?

If it is already documented somewhere, then sorry for those questions :)
If not, please document it somewhere 👍

**Comment by Robert95Sch** [comment]
Hi @AndreasAugustin and sorry for the delayed response. The connection to the databases itself can be encrypted and SSL is configured, but the databases are not encrypted@rest. The databases are currently not publicly accessible.

We will add the missing information to our docs, thanks for the hint!

Best,
Robert
