### ISSUE TITLE
Deployed HTML Page have to reload

### ISSUE THREAD

**Issue by baniasbaabe** [ionos-deploy-now/ionos-deploy-now#77]
After deploying my plain HTML/CSS website, when I go to the website via mobile, the page is initially only loading like 20% of the page. I always have to reload it so that the full page loads.

**Comment by Robert95Sch** [comment]
Hi @baniasbaabe , I couldn't find a technical reason for the issue on the product side. Looks like you've deleted your project, so I cannot investigate your code. Feel free to reach out to [deploynow-support@ionos.com](mailto:deploynow-support@ionos.com) if you decide to set up a project again and need support. 

Sorry for the late reply!
Best
Robert
