### ISSUE TITLE
I love the simplicity, but...

### ISSUE THREAD

**Issue by aschelch** [ionos-deploy-now/ionos-deploy-now#81]
Hi, 

I like the simplicity of deploy-now but there is one thing that is not very clear to me or I don't understand it.
It concerne the capability to override some PHP ini settings from htaccess. Is it something possible ?

Because I tried to increase post_max_size from it, and it does not change anything..

I tried to set the limit using php_value in .htaccess.template file in .deploy-now folder. But I does not seems to works.
I added that :

    <IfModule mod_php.c>
        php_value upload_max_filesize 200M
        php_value post_max_size 200M
    </IfModule>

I also tried with module php_module but didn't work either.
I also verified that the .htaccess is containing my modification from Deployment viewer.

Did I miss something?

Thanks ;)

**Comment by agaengel** [comment]
Hi aschelch,

unfortunately it is not possible to change the php values in deploy now.

Regards
Alex

**Comment by aschelch** [comment]
Hi Alex,
So there is now way to increase uploaded max file size ? 😰
If so, no other choice than moving out from DeployNow 😕

**Comment by Robert95Sch** [comment]
Hi @aschelch and thanks for your feedback.

I will discuss possible solutions with our platform team, but I cannot promise any short-dated solution yet. 
I'm sorry to disappoint you.

Best,
Robert

**Comment by agaengel** [comment]
Hi  @aschelch,

it is possible to provide an own php.ini in the root directory of the project.

so if you add a php.ini with the content:
upload_max_filesize = 200M
post_max_size = 200M

these values will be uses.

Sorry I was not aware that you can provide you own php.ini

Regards
Alex

**Comment by aschelch** [comment]
Oh nice, I will try that asap! 
Thanks a lot for this great news 😁

**Comment by agaengel** [comment]
@aschelch please put the php.ini in the public folder next to your index.php

I am not aware of performance issues do you still seeing them

Regards
Alex
