### ISSUE TITLE
Next JS (API) deploy support

### ISSUE THREAD

**Issue by rodolfogamd** [ionos-deploy-now/ionos-deploy-now#86]
# Feature request

## Description

It would be nice to be able to deploy Next JS (API) apps as well as we can do with Next JS (Static) apps now

## Value

This will allow hosting more applications and include potential clients who use Next JS (API) to use your service to host their apps.

## Approach

Since you already use Node JS for deploying Next JS (Static) apps, we could leverage that configuration also to include support for Next JS (API) apps.

**Comment by ionos-deploy-now-support** [comment]
Thanks for your message, server side rendering is not currently supported im afraid.

**Comment by Robert95Sch** [comment]
Hi @rodolfogamd and thanks for your request,

the request for Node.js support has been made multiple times already and we would love to enable the support to also offer full Next.js support. However, supporting Node.js would come with larger changes for the infrastructure Deploy Now is currently deploying to. We'll do our best to make a prioritization happen.

Thanks for your feedback & we'll keep you posted,
Robert - Product Owner
