### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by pfaffenrodt** [ionos-deploy-now/ionos-deploy-now#87]
```
Run ionos-deploy-now/deploy-to-ionos-action@v1
/usr/bin/docker run --name ghcrioionosdeploynowdeploytoionosv118_c7b50f
.....
Trigger creation of temporary user
Failed to create temporary user
```

Reporting bug also here. Dont trusting bug reports in deploy now. It is not validating errors.
Having issues whole week und not receiving any help. Called support and the devs wanted a bug report via deploy now. 
Looking in dev tools, reporting bug had a validation error. 

Rename the product to deploy next year, it fits better. All good, until it is not.

**Comment by cetiny** [comment]
I have the same issue 
![image](https://user-images.githubusercontent.com/47256950/228638178-7261ad24-9b91-473b-8d7f-2b39b7ab84ee.png)

**Comment by pfaffenrodt** [comment]
I just deleted the project and recreated it. It seems, that they refactored the github workflows. 
It works with with V2.

**Comment by pfaffenrodt** [comment]
@cetiny Do need this issue ticket. I am done with it. Recreate project will solve this issue

**Comment by cetiny** [comment]
Thank you. I will try that. You can close it.
