### ISSUE TITLE
Failed to create temporary user

### ISSUE THREAD

**Issue by danielluca** [ionos-deploy-now/ionos-deploy-now#88]
Deployment is failing on a preview branch in step: deploy to ionos with the error: Failed to create temporary user.

```yaml
Trigger creation of temporary user
Failed to create temporary user
```

**Comment by ionos-deploy-now-support** [comment]
Our API responds with the wrong http status code, which is interpreted as an error.
the deploy-to-ionos-action was updated and all old workflows should work now.
