### ISSUE TITLE
Deploy Now with Angular

### ISSUE THREAD

**Issue by HoschiAndre** [ionos-deploy-now/ionos-deploy-now#91]
I do get an 403. Pipeline did run fine. Please let me know. 

Hotline is busy for 30 min ... and then I'm not passion enough :-) anymore. I send an Email as well til now no answer. 

Crying for help! 

Cheers,
Andre

**Comment by ionos-deploy-now-support** [comment]
Hello thank you for your message, your .dist should be defined as follow:
./dist/simplemetric-landingpag

**Comment by HoschiAndre** [comment]
Hello ... thanks for your response. I have changed the folder accordingly but still have the same error.

**Comment by HoschiAndre** [comment]
Hello thanks for the response and the hint. It was just the ./dist Folder without the subfolder simplemetric-landingpage

Cheers!!
