### ISSUE TITLE
"Deploy to IONOS" step faild

### ISSUE THREAD

**Issue by issam-brayche** [ionos-deploy-now/ionos-deploy-now#93]
Hello,
I'am trying the Deploy Now feature for the first time with a Laravel project.
I have a fail on the "Deploy to IONOS" step from the workflow. The error is "Error: Php commands defined in post deployment remote commands although php is disabled" (see picture below)
<img width="942" alt="Screenshot 2023-05-08 at 17 28 10" src="https://user-images.githubusercontent.com/20924553/236867202-01105a0d-fcb6-4978-8d0b-d7ba299b52aa.png">

Do you have any idea on how to resolve this problem ?

Thank you,

**Comment by ionos-deploy-now-support** [comment]
Hi, thank you for contacting us, to use Laravel starter, you must select the PHP project , i can see in your account that you use "starter"
