### ISSUE TITLE
Error 403 when deploying React project

### ISSUE THREAD

**Issue by stevenzieske** [ionos-deploy-now/ionos-deploy-now#94]
Hello all,

when I deploy my React JS / Vite project I get the error 403.
I changed the path to dist when I created the workflow, connected it to a domain and everything looks fine in my deployment viewer. The workflow runs through in GitHub Actions so far without any problems that I can see.
I have already tried the suggestion from #91 which did not help.
Here is the [Link](https://github.com/stevenzieske/stevenzieske.de) to the repo.

Thanks in advance

**Comment by ionos-deploy-now-support** [comment]
Thank you for your message, i will investigate this issue and contact you via email.


regards.
