### ISSUE TITLE
Set domain for staging deployments

### ISSUE THREAD

**Issue by pmanandhar1452** [ionos-deploy-now/ionos-deploy-now#95]
# Feature request

## Description

You used to have domain setting for staging deployments. Now it seems to be removed. We need this to smooth our authentication and test workflows where we want to use our own domain for test and not the ionos domain.

## Value

We want to have a uniform convention to use something like test.mydomain.com to test and not a random url generated by IONOS.

## Approach

This used to be a feature. Please bring it back.

**Comment by ionos-deploy-now-support** [comment]
https://github.com/ionos-deploy-now/ionos-deploy-now/issues/17
thank you for your request i can see this has been asked before. sadly in not currently in our roadmap.,
