### ISSUE TITLE
can't deploy from sample and edit permissions in GitHub within ionos.com

### ISSUE THREAD

**Issue by rodemann** [ionos-deploy-now/ionos-deploy-now#96]
Hi,

when I try to deploy from a sample within ionos.space/setup, I get an 500 error. Maybe related: I cannot update my github permissions from there. https://github.com/apps/ionos-deploy-now/installations/d4de35b4-f209-4af2-ab28-3a84a0141e68/permissions gives me an 404 error. 

Your help is much appreciated! Thank you!

**Comment by ionos-deploy-now-support** [comment]
Hello, thank you for contacting us, i believe this was solve yesterday though email address,

if you have any more questions, we would be happy to answer.

**Comment by rodemann** [comment]
Hi, 
Thanks for getting back to me. I'm afraid you're confusing me with someone else. The issue still exists. Thanks in advance for your kind help!

**Comment by rodemann** [comment]
?

**Comment by ionos-deploy-now-support** [comment]
Sorry for the late response, im contacting you via email
