### ISSUE TITLE
How do I use/configure frameworks for Deploy-Now?

### ISSUE THREAD

**Issue by Lyso95** [ionos-deploy-now/ionos-deploy-now#98]
### Discussed in https://github.com/orgs/ionos-deploy-now/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **Lyso95** May 24, 2023</sup>
Hey, 

am I just too dump to host an application? This "One-Click-Thing" isn´t working for me.

I am continuously running into: 403 Forbidden
Forbidden
You don't have permission to access this resource.

When trying to host something. I managed to publish the template of next:
https://home-5013132557.app-ionos.space/ 

But when I try to do something else like: 
https://github.com/Lyso95/next-portfolio
with
https://nextra.site/

or

https://github.com/Lyso95/reactvite_test
with
https://vitejs.dev/

I get stuck everytime...

Can you give me a hint? Found this in docs, but don´t get the clue how to config.
https://docs.ionos.space/docs/apache-configuration-htaccess/

Thank you for you help!</div>

**Comment by agaengel** [comment]
I just left a comment in the discussion with the hint that you build does not generate an index.html

Regards
Alex
